- name: Open port for RedHat
  ansible.posix.firewalld:
    port: '9100/tcp'
    permanent: true
    state: enabled
  notify:
    - Restart Firewalld
  when: ansible_facts['os_family'] == "RedHat"
  
- name: Open port for Debian
  ansible.builtin.iptables:
    chain: INPUT
    rule_num: '1'
    action: insert
    protocol: tcp
    jump: ACCEPT
    destination_port: '9100'
  when: ansible_facts['os_family'] == "Debian"