---
# tasks file for common-role
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
    
- name: Stop SELinux
  ansible.builtin.shell: setenforce 0
  ignore_errors: true

- name: Open ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 3000/tcp
    - 9090/tcp
  notify:
    - Restart Firewalld